<html>
<body>
<table width="100%" cellpadding="0" cellspacing="0" style="font-family:Avenir,Helvetica,sans-serif;box-sizing:border-box;background-color:#f5f8fa;margin:0;padding:0;width:100%">
   <tbody>
      <tr>
         <td align="center" style="font-family:Avenir,Helvetica,sans-serif;box-sizing:border-box">
            <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Avenir,Helvetica,sans-serif;box-sizing:border-box;margin:0;padding:0;width:100%">
               <tbody>
                  <tr>
                     <td style="font-family:Avenir,Helvetica,sans-serif;box-sizing:border-box;padding:25px 0;text-align:center">
                        <a target="_blank" href="{{url('/')}}">
                         <img src="{{ asset('public/images/logo.png') }}" width="50%;" alt="My Health Squad Logo">
                        </a>
                     </td>
                  </tr>
                  <tr>
                     <td width="100%" cellpadding="0" cellspacing="0" style="font-family:Avenir,Helvetica,sans-serif;box-sizing:border-box;background-color:#ffffff;border-bottom:1px solid #edeff2;border-top:1px solid #edeff2;margin:0;padding:0;width:100%">
                        <table align="center" width="60%;" cellpadding="0" cellspacing="0" style="font-family:Avenir,Helvetica,sans-serif;box-sizing:border-box;background-color:#ffffff;margin:0 auto;padding:0;width:60%;">
                           <tbody>
                              <tr>
                                 <td style="font-family:Avenir,Helvetica,sans-serif;box-sizing:border-box;padding:35px">
                                    <span class="im">
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:3.0pt;margin-left:0in;line-height:115%;font-size:35px;font-family:"Arial","sans-serif";text-align:center;'><strong><span style="font-size:24px;line-height:115%;">GENERAL CONDITIONS OF CONTRACT&nbsp;</span></strong></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>&nbsp;</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>By signing this document, the Client expressly accepts the General Terms and Conditions of the contract.</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><span style="color:black;"><br> <strong>1.&nbsp; &nbsp; &nbsp;PURPOSE&nbsp;</strong></span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>The following Terms of Purchase, along with the Terms of Use and Privacy</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>Policy located at &nbsp; <a target="_blank" href="{{url('privacy-policy')}}">{{url('privacy-policy')}}</a>, the Specific Terms of Contract Sheet constitute your entire agreement (the &#39;Agreement&#39;) with My Health Squad., tax no. ____________ Address _____________ (hereinafter, &#39;{{url('/')}}&#39;) and its client (the &#39;Client&#39; or &#39;you&#39;), in accordance with what is stated in the Specific Terms of Contract Sheet, to provide services (the &#39;Service&#39;) related to the {{url('/')}} Web site (the &#39;Website&#39;).</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>The Client may only use the Service in its capacity as an end client. The re-selling, marketing, or transferring of the Service is not authorized. Similarly, given its status as a professional within the industry in which</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'> {{url('/')}} provides its Service, the CLIENT shall not be considered a consumer.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><span style="color:black;">2. <strong>&nbsp; &nbsp;&nbsp;DATA PROTECTION POLICY</strong></span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>The parties agree to comply with current legislation on personal data protection.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;2.1. With regards the Service, the CLIENT clearly states its commitment to:</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>Apply, process and use the personal data it has access to in accordance to applicable Ontario legislation. Services provided by</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>{{url('/')}} in other provinces may also be subject to local legislation on personal data protection and services provided over the Internet.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>- &nbsp;Access data held on record only in accordance with the explicit and legitimate purposes of this Agreement.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>- &nbsp;Not transfer personal information to individuals or legal entities other than those that may have been expressly authorised by virtue of this Agreement.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>- &nbsp;Agree to protect the personal information it has access to guarantee its confidentiality and to prevent unauthorised third parties from accessing said information.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>- &nbsp;Be responsible for the illegal use of information belonging to those people who have registered or provided any protected information. For the purposes of this Section, illegal use shall be considered as the use of said information contrary to applicable Ontario laws or other applicable law in a different way or for a purpose other than the aim of this Agreement.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>- &nbsp;Keep username(s) and password(s) secret and to manage all CLIENT access to {{url('/')}} with care.&nbsp;</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;2.2. In terms of compliance with Ontario law, {{url('/')}} clearly states its commitment to:</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>- &nbsp;Apply, process and use the personal data it has access to in accordance with all applicable legislation.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>- &nbsp;Be responsible for the illegal use of the information belonging to those people who have registered or provided any protected information. For the purposes of this Section, illegal use shall be considered to be the use of information contrary to applicable legislation or regulations or in a different way or for a purpose other than the object of this Agreement.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>- &nbsp;Have obtained the data and information in the database of {{url('/')}} Clients from the Client themselves when contracting the Service.&nbsp;</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>&nbsp;</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><span style="color:black;"><br> <strong>3</strong>. <strong>&nbsp; &nbsp;&nbsp;LIABILITIES, REPRESENTATIONS &amp; GUARANTEES</strong></span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>3.1. The CLIENT agrees that its use of the Service shall not be linked to any illegal activity or any activity that threatens the image of {{url('/')}}, individuals, or third parties. In particular, the CLIENT agrees that it will strictly comply with all legislation of any kind that affects, either directly or indirectly, its activity on the Website and its professional development related to the Service, expressly releasing {{url('/')}} from any possible liability arising from a breach of any of these responsibilities. {{url('/')}} may carry out relevant investigations and request any documentation that it considers necessary so as to verify compliance with the aforementioned responsibilities.<br>&nbsp;</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>3.2. The CLIENT declares and guarantees that the uploading of content and logos belonging to the CLIENT on the Website does not and will not breach or violate any legal obligation or agreements entered into with third parties.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;3.3. All information provided by the CLIENT to {{url('/')}} must be correct, up-to-date and reflect the current situation. For this purpose, the CLIENT guarantees that the information provided as a result of the Service is genuine. The CLIENT shall be responsible for keeping all information provided to {{url('/')}} constantly up-to-date and for ensuring that it reflects the CLIENT&#39;s current status at all times. The CLIENT shall, in any event, be solely responsible for any false or inaccurate statements it makes and for the damage that this may cause to {{url('/')}} or to third parties.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;3.4. {{url('/')}} shall not be liable for the outcome of transactions undertaken through the Website.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;3.5. The CLIENT is responsible for sending {{url('/')}} all the materials and information required to correctly execute this Agreement at least 21 days prior to the start of the Service and in the manner stated by</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>{{url('/')}}. In the event the CLIENT does not comply with this obligation and the purpose of the Agreement cannot be executed, the CLIENT shall not be able to demand a return, payment or compensation of any kind from {{url('/')}} and the Service may be terminated or suspended.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;3.6. {{url('/')}} shall not mediate or be involved in internal conflicts between CLIENTS or between CLIENTS and third parties that may interfere with the correct provision of the Service offered by {{url('/')}}. CLIENT is solely responsible for resolving the disputes. {{url('/')}} reserves the right to terminate in advance the Agreement with any CLIENT or suspend the Service until the conflicts have been resolved satisfactorily and in full.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>&nbsp;</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><span style="color:black;"><br> <strong>4.</strong> <strong>&nbsp; &nbsp;&nbsp;COST AND PAYMENT TERMS</strong></span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>4.1. In return for the Service, the CLIENT shall pay {{url('/')}} the total amount stated in the Specific Terms of Contract Sheet, under the payment terms indicated therein. The prices stated do not include taxes, including, without limitation, GST and HST, which shall be applied in the invoice at the current rate, where applicable. In the event the CLIENT is unable to benefit from the contracted Services as a result of the Service being cancelled due to non-payment, as set out in Section 4.3 below, the CLIENT shall not be able to demand the refund or payment of the amounts applicable to the cancelled period arising from non-payment.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;4.2. Twenty-five (25%) percent of the total amount stated in the Specific Terms of Contract Sheet refers to activities that are fundamental for the implementation of the Service or its renewal. The CLIENT shall therefore be obliged to pay this amount in any event and shall not be entitled to any refunds or offsets for this amount.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;4.3. The CLIENT is obliged to make all payments on time by virtue of this</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>Agreement. If the CLIENT does not comply with the established payment terms, {{url('/')}} may automatically cancel the Service provided and remove the CLIENT from the Website.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>If, for any reason, any fees the Client owes {{url('/')}} have not been received or in any manner realized by {{url('/')}} (&#39;Unpaid Fees&#39;), Client agrees to pay such Unpaid Fees immediately. In addition, WeddingWire may charge interest, in the lower amount of 2.0% per month (24% per annum) or the maximum amount allowed by law, on any unpaid account balance that Client maintains. Any partial payments made by Customers will first be applied to the most recent fees owed to {{url('/')}}, including interest.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;4.4. If the Service is cancelled for this reason, {{url('/')}} may not re-establish the Service until the outstanding amounts have effectively been paid. {{url('/')}} may demand that the CLIENT pays default interest or any other cost arising from or linked to bank commissions and payments claimed back.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;4.5. In the event that all or some of the Agreement purpose is made up of one or several Services to be instantly executed and all or some of said Services could not be provided by {{url('/')}} for any reason attributable to the CLIENT, the CLIENT must pay the cost of said Services in full, without prejudice to the provisions regarding the inability to provide any specific Service in question in the Agreement, in the event the Agreement contains other ongoing Services.</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><span style="color:black;"><br> <br> <strong>5. &nbsp; &nbsp;&nbsp;INTELLECTUAL &amp; INDUSTRIAL PROPERTY</strong></span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>5.1. The content on the Website is protected by intellectual and industrial property legislation.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;5.2. The CLIENT gives its consent for its brands and commercial logos to be used by {{url('/')}}. Similarly, the CLIENT gives its consent for {{url('/')}} to use content uploaded by the CLIENT to the Website or sent to {{url('/')}} by any means for inclusion on the Website.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;5.3. The CLIENT clearly states that none of the content provided to</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>{{url('/')}} violates in any way intellectual or industrial property rights, or rights of any other kind, owned by third parties, expressly releasing and exempting {{url('/')}} from any claim relating to this sphere brought by any third party and fully assuming responsibility for these events. {{url('/')}} reserves the right to remove any content that may violate the rights of third parties and, in particular, the fundamental rights of third parties.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;5.4. Each party shall immediately inform the other of any breach of the other party&#39;s intellectual or industrial property rights, of which they were aware, and shall assist in full in defending said rights.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><strong><span style="color:black;">6. &nbsp; &nbsp;&nbsp;ENTRY INTO FORCE &amp; SERVICE TERM</span></strong></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>6.1. This Agreement shall enter into force when the CLIENT agrees to and accepts the Agreement. The CLIENT shall be understood to have agreed and accepted from the moment when it confirms acceptance of the Agreement via any of the means provided herein.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;6.2. The Service shall begin promptly after {{url('/')}} receives confirmation that the CLIENT has agreed to the terms of the Agreement for the Service, together with the information required to activate said Service.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;6.3. The Agreement term length is indicated in the Specific Terms of Contract Sheet. When the Agreement is for immediate execution and not for ongoing Services, the term of said Agreement shall be included in the Specific Terms of Contract Sheet. If no term length is specified in the Specific Terms of Contract Sheet, the default contract length shall be one (1) year. If you purchase an upsell or additional product or service, the term length of such upsell or additional product or service, unless specified in the Specific Terms of Contract Sheet, shall be co-terminous with the term of the initial Service specified in the Specific Terms of Contract Sheet, even if less than one (1) year. Following termination of the Agreement, the CLIENT may remain on the Website, included in a free service, provided that {{url('/')}} and the Website has availability. In the event of any termination or expiration of the Agreement, {{url('/')}} shall retain the right to keep any and all reviews of CLIENT posted on the Website as well as basic directory information of CLIENT associated with such reviews, including, without limitation, business name, address, and telephone number.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><strong><span style="color:black;">7. &nbsp; &nbsp;&nbsp;REASONS FOR TERMINATION</span></strong></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>This Agreement may be terminated in the following cases:</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;7.1. By {{url('/')}} in the event the CLIENT does not comply with any of its responsibilities contained in this Agreement and does not rectify said non-compliance within seven (7) calendar days from when said responsibility expires, or from when awareness is acquired of the aforementioned circumstance. During this time {{url('/')}} may limit or cancel the Service without the CLIENT being exempted from making payments during the cancelled and/or limited period.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;7.2. At the discretion of {{url('/')}}, and at any moment, even though the services will actually be cancelled on the same day of the month as the day on which the Agreement entered into force.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;7.3. By {{url('/')}} unilaterally without prior notice in the following circumstances:</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>- &nbsp;provided that it detects and can provided technical evidence to show that the CLIENT has maliciously used the Service.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>- &nbsp;for being involved in any type of dispute between CLIENTS or between a CLIENT and a third party.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>- &nbsp;as a result of repeated complaints by users of the Website, upon prior verification by {{url('/')}}.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>- &nbsp;in the event the CLIENT refuses to provide the relevant requested documentation by {{url('/')}} in connection with the representation contained in Section Thirteen below, or who clearly and deliberately hides said documentation and violates any applicable legislation.&nbsp;</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><strong><span style="color:black;">8. &nbsp; &nbsp;&nbsp;APPLICABLE LEGISLATION &amp; JURISDICTION</span></strong></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>This Agreement shall be governed by Ontario and Canadian legislation, which shall be applied to the validity, interpretation, execution and compliance thereof. In particular, any relationship between the CLIENT and {{url('/')}} shall also be governed by the Website&#39;s Terms of Use and Privacy Policy at&nbsp;</span><a target="_blank" href="{{url('terms')}}"><span style='font-family:"Calibri","sans-serif";color:windowtext;'>{{url('terms')}}</span></a><span style='font-family:"Calibri","sans-serif";'>. Any claim or controversy arising out of or relating to CLIENT&#39;S use of the Website, to the goods or services provided through the Website, this Agreement, or to any acts or omissions for which CLIENT may contend {{url('/')}} is liable, including but not limited to any claim or controversy as to arbitrability (&#39;Dispute&#39;), shall be finally, and exclusively, settled by arbitration, as further specified in Section Nine, below. Only the extent that the arbitration provisions are inapplicable or unenforceable with regard to a particular Dispute, such Dispute shall be submitted to the Courts and Tribunals of the province of Ontario. Consequently, both parties expressly renounce their own jurisdiction. If either party employs attorneys to enforce any right in connection with any Dispute or lawsuit, the prevailing party shall be entitled to recover reasonable attorneys&#39; fees.</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><span style="color:black;"><br> <br> <strong>9. &nbsp; &nbsp;&nbsp;ARBITRATION</strong></span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>Disputes between CLIENT and {{url('/')}} regarding the Website and our Service should be reported to&nbsp;</span><a target="_blank" href="mailto:support@myhealthsquad.ca"><span style='font-family:"Calibri","sans-serif";color:windowtext;'>support@myhealthsquad.ca</span></a><span style='font-family:"Calibri","sans-serif";'>&nbsp;{{url('/')}} will attempt to resolve any disputes CLIENT has with us. Because the Website is a neutral venue, {{url('/')}} is not responsible for resolving any disputes between CLIENT and members regarding services or transactions. In accordance with Section Eight, above, any arbitration related to a Dispute shall be held before one arbitrator under the commercial arbitration rules of Ontario. The arbitration shall be conducted in Toronto. The arbitrator shall be selected pursuant to Ontario law. In any arbitration, the parties will split the cost of the filing fee, plus the costs associated with the first day of arbitration, with the remaining costs of arbitration paid by the non-prevailing party. To begin the arbitration process, a party must make a written demand. Any judgment upon an award rendered by the arbitrators may be entered in any court in Toronto. The arbitrators shall not have the power to award damages in connection with any Dispute in excess of actual compensatory damages and shall not multiply actual damages or award consequential, punitive or exemplary damages, and each party irrevocably waives any claim thereto. The agreement to arbitrate shall not be construed as an agreement to the joinder or consolidation of an arbitration under this Agreement with an arbitration of disputes or claims of any non-party, regardless of the nature of the issues or disputes involved.<br>&nbsp;</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>THIS AGREEMENT PROVIDES THAT ALL DISPUTES BETWEEN THE CLIENT AND {{url('/')}} WILL BE RESOLVED BY BINDING ARBITRATION. CLIENT THUS GIVES UP ITS RIGHT TO GO TO COURT TO</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>ASSERT OR DEFEND ITS RIGHTS. IT ALSO GIVES UP ITS RIGHT TO PARTICIPATE IN OR BRING CLASS ACTION LAWSUITS. CLIENT&#39;S RIGHTS WILL BE DETERMINED BY NEUTRAL ARBITRATORS AND NOT A JUDGE OR JURY. Parties to arbitration are entitled to a fair hearing, but the arbitration procedures are simpler and more limited than rules applicable in court. Arbitrator decisions are enforceable as any court order and are subject to very limited review by a court. By agreeing to this AGREEMENT, CLIENT consents to these restrictions.</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><span style="color:black;"><br> <br> <strong>10. &nbsp;&nbsp;CURRENCY</strong></span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>CLIENTS will be billed in Canadian Dollars.</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><span style="color:black;"><br> <br> <strong>11. &nbsp;&nbsp;WARRANTY EXCLUSION</strong></span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>THE PRODUCTS AND/OR SERVICES PROVIDED BY {{url('/')}} ARE PROVIDED &#39;AS IS&#39;, &#39;AS AVAILABLE&#39; WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT POSSIBLE PURSUANT TO THE APPLICABLE LAW, {{url('/')}} DISCLAIMS ALL WARRANTIES, EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT OR OTHER VIOLATION OF RIGHTS. THE PRODUCTS AND/OR SERVICES MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS, INCLUDING, WITHOUT LIMITATION, WARS, TERRORIST ATTACKS, STRIKES, RIOTS, EARTHQUAKES, HURRICANES, TORNADOES, VOLCANOES, MAJOR WEATHER EVENTS, INTERNET CONGESTION, ATTACKS ON OR FAILURE OF INFRASTRUCTURE, TROJAN, VIRUS OR MALWARE, AND DENIAL OF SERVICE (DOS) ATTACKS (THE &#39;FORCE MAJEURE EVENTS&#39;). {{url('/')}} IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM THESE FORCE MAJEURE EVENTS. </span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><span style='font-size:19px;line-height:115%;font-family:"Calibri","sans-serif";color:black;'><br>&nbsp;</span><span style="color:black;"><br> <strong>12. LIMITED LIABILITY</strong></span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>IN NO EVENT SHALL {{url('/')}}, OUR AFFILIATES, EMPLOYEES, OFFICERS, DIRECTORS, SHAREHOLDERS, OR SUPPLIERS BE LIABLE TO CLIENT OR ANYONE ELSE FOR INDIRECT DAMAGES, LOST PROFITS, ANY SPECIAL, INCIDENTAL, RELIANCE, OR CONSEQUENTIAL DAMAGES, OR DAMAGES OF ANY KIND WHATSOEVER ARISING OUT OF OR RELATING TO THE USE OF OR INABILITY TO USE THE SITE, FOR USE OF ANY COUPONS OR OTHER PROMOTIONAL DISCOUNTS, OR FOR ANY DECISION MADE OR ACTION TAKEN BY YOU IN RELIANCE ON INFORMATION CONTAINED ON THE SITE, WHETHER IN AN ACTION FOR BREACH OF WARRANTY OR CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, AND NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY REMEDY. {{url('/')}}&#39;S LIABILITY, AND THAT OF OUR AFFILIATES, EMPLOYEES, OFFICERS, DIRECTORS, SHAREHOLDERS, OR SUPPLIERS, TO CLIENT OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO THE LESSER OF THE AMOUNT OF FEES YOU PAY TO {{url('/')}} IN THE 12 MONTHS PRIOR TO THE ACTION GIVING RISE TO LIABILITY OR $100, NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY REMEDY.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'><br>&nbsp;</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><strong><span style="color:black;">13. &nbsp;&nbsp;REPRESENTATION AND WARRANTY</span></strong></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>The person consenting to this Agreement represents and warrants that: (1) such person has authority to enter into it on behalf of Client; (2) Client&#39;s entering into this Agreement does not violate any other rights, obligations, regulations or laws; (3) Client has obtained all necessary rights for any content that it provides to {{url('/')}} and that {{url('/')}} &#39;s use</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>of such content will not be defamatory or harassing or violate any third party rights, including rights of publicity, privacy, and intellectual property rights, or violate any law or regulation; (4) declares that the Client strictly complies with all legislation and requirements, of any type, that affect, either directly or indirectly, its business and its professional performance, expressly releasing</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>{{url('/')}} from any possible liability arising from a breach of any of its responsibilities. {{url('/')}} may carry out relevant investigations and request any documentation that it considers necessary so as to verify compliance with the aforementioned duties.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>{{url('/')}} reserves the right to rely on the representations and warranties made by any authorized user of Client&#39;s account when providing the services to Client.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>&nbsp;</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>&nbsp;</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><strong><span style="color:black;">14. &nbsp;&nbsp;INDEMNITY</span></strong></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>Client agrees to indemnify and hold {{url('/')}} and our affiliates, officers, directors, agents, and employees harmless from any claim or demand, including reasonable attorneys&#39; fees, made by any third party due to or arising in any manner in whole or in part out of Client&#39;s use of the Website and/or its violations of its representations, warranties or obligations under the Agreement.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>&nbsp;</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>&nbsp;</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><strong><span style="color:black;">15. &nbsp;&nbsp;ASSIGNABILITY</span></strong></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>You may not assign this Agreement or any of your rights or obligations under this Agreement to any party without {{url('/')}}&#39;s prior written consent. {{url('/')}} may assign this Agreement or any of its rights or obligations under this Agreement to an affiliate or related party or to an acquirer, purchaser of all or substantially all of the assets of {{url('/')}}, successor in interest or surviving entity as the result of merger or acquisition or other third party. {{url('/')}} may pledge this Agreement as collateral or may grant security interests in the Agreement.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>&nbsp;</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><span style="color:black;"><br> <strong>16. &nbsp;&nbsp;LANGUAGE</strong></span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>The parties have expressly agreed that this agreement and all ancillary agreements, documents or notices relating thereto be drafted solely in the English language. Les parties aux pr&eacute;sentes ont express&eacute;ment convenu que ce accord et toute autre convention, document ou avis y aff&eacute;rent soient r&eacute;dig&eacute;s en anglais seulement.</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>&nbsp;</span></p>
                                       <p style='margin-top:0in;margin-right:0in;margin-bottom:16.0pt;margin-left:0in;line-height:115%;font-size:20px;font-family:"Arial","sans-serif";color:#666666;'><span style="color:black;"><br> <strong>17. &nbsp;&nbsp;GENERAL TERMS OF CONTRACT</strong></span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>The Client has read and accepts the Purchase Confirmation Sheet and these terms in full and without reservations, as well as any other applicable specific terms and the Website&#39;s Terms of Use and Privacy Policy located at&nbsp;</span><a target="_blank" href="{{url('privacy-policy')}}"><span style='font-family:"Calibri","sans-serif";color:windowtext;'>{{url('privacy-policy')}}</span></a><span style='font-family:"Calibri","sans-serif";'>&nbsp; The way in which this Agreement is signed does not alter its validity and both a signed paper copy of the Agreement and an electronically signed Agreement are equally valid.&nbsp;</span></p>
                                       <p style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:19px;font-family:"Arial","sans-serif";'><span style='font-family:"Calibri","sans-serif";'>&nbsp;</span></p>
                                    </span><br>
                                    <p style="font-size: 12px;"><i>Unsubscribe from My Health Squad emails</i><a target="_blank" href="{{url('email-unsubscribe/'.(isset($toEmail)?encrypt($toEmail):''))}}" style="text-decoration: none;"> Click here</a></p>
                                 </td>
                              </tr>
                           </tbody>
                        </table>
                     </td>
                  </tr>
                  <tr>
                     <td style="font-family:Avenir,Helvetica,sans-serif;box-sizing:border-box">
                        <table align="center" width="570" cellpadding="0" cellspacing="0" style="font-family:Avenir,Helvetica,sans-serif;box-sizing:border-box;margin:0 auto;padding:0;text-align:center;width:570px">
                           <tbody>
                              <tr>
                                 <td align="center" style="font-family:Avenir,Helvetica,sans-serif;box-sizing:border-box;padding:35px">
                                    <p style="font-family:Avenir,Helvetica,sans-serif;box-sizing:border-box;line-height:1.5em;margin-top:0;color:#aeaeae;font-size:12px;text-align:center">&copy; {{date('Y')}} <span class="il">My </span> <span class="il">Health</span> Squad. All rights reserved.</p>
                                 </td>
                              </tr>
                           </tbody>
                        </table>
                     </td>
                  </tr>
               </tbody>
            </table>
         </td>
      </tr>
   </tbody>
</table>
</body>
</html>